name: Gustavo Andrade
favicon: null
layout_spectrum: 0.10944
typography_spectrum: 0.011451110010966659
title: Gustavo Andrade
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.5438154698349535
  rhythmicContrast: 0.75
purpose: []
