name: Gustavo Andrade
favicon: null
layout_spectrum: 0.10944
typography_spectrum: 0.13332
title: Gustavo Andrade
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a050d'
    - '#fdfdfd'
    - '#4e4e4c'
    - '#d17223'
    - '#ff0000'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
